/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tests;

import static com.mycompany.tests.Tests.LB;
import static com.mycompany.tests.Tests.NBE;
import static com.mycompany.tests.Tests.R;
import static com.mycompany.tests.Tests.r;

/**
 *
 * @author Hicham
 */
public class test extends javax.swing.JFrame {

    private double LB ;
    private double R;
    private double NBR;
    private double r;
    private  double FR ;
    private double  TR ;
    private final double P0 = 608.63 ; 
    private int n ;
    private double credit;
    private double prix ; 
    private double Cra , C =  1 ;
    private  double RF = 6.42 , AF=20 , PR=1168.42 ;
    private double AE;
    private int trim;
    
    public test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nbrtt = new javax.swing.JTextField();
        lb = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        supEtage = new javax.swing.JTextField();
        avence = new javax.swing.JTextField();
        trimnbr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sup = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        fraibrachement = new javax.swing.JTextField();
        taxeRE = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        provision = new javax.swing.JTextField();
        redevancef = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        autresFrais = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        BS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comptant = new javax.swing.JRadioButton();
        trimistrialite = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nbrtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 129, -1));

        lb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbActionPerformed(evt);
            }
        });
        getContentPane().add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 129, -1));

        jButton1.setText("calculer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 110, 50));
        getContentPane().add(supEtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 130, 30));

        avence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avenceActionPerformed(evt);
            }
        });
        getContentPane().add(avence, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 150, 20));
        getContentPane().add(trimnbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 150, -1));

        jLabel1.setText("comptant");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 60, -1));

        jLabel2.setText("par trimistrialite");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 120, 30));
        getContentPane().add(sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 130, 20));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(fraibrachement, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 110, 30));
        jPanel1.add(taxeRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 110, 30));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 100, 20));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 100, 20));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 100, 20));

        provision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provisionActionPerformed(evt);
            }
        });
        jPanel1.add(provision, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 110, 20));

        redevancef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redevancefActionPerformed(evt);
            }
        });
        jPanel1.add(redevancef, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 110, 30));

        jLabel3.setText("frais de branchement");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel4.setText("Taxe reveraine");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel5.setText("Provision");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel6.setText("Redevance fix");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel7.setText("timbre");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 70, -1));

        jLabel8.setText("total a payer");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 100, 30));

        autresFrais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autresFraisActionPerformed(evt);
            }
        });
        jPanel1.add(autresFrais, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 110, 30));
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 110, 40));

        jLabel13.setText("credit B.S");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 90, 20));
        jPanel1.add(BS, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 540, 260));

        jLabel9.setText("Veuillez entrer la superficie du lot :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, 40));

        jLabel10.setText("Veuillez entrer le nombre d'etage:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel11.setText("Veuillez entre la longueur de branchement");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel12.setText("Veuillez entrer la superficie de l'étage :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 220, 20));

        buttonGroup1.add(comptant);
        comptant.setText("comptant");
        comptant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comptantActionPerformed(evt);
            }
        });
        getContentPane().add(comptant, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        buttonGroup1.add(trimistrialite);
        trimistrialite.setText("par trimistrialite");
        trimistrialite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trimistrialiteActionPerformed(evt);
            }
        });
        getContentPane().add(trimistrialite, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, -1));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avenceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        LB=Integer.parseInt(nbrtt.getText());
//        NBR=Integer.parseInt(lb.getText());
//        R=Integer.parseInt(sup.getText());
//       r=Integer.parseInt(supEtage.getText());
//       AE=Integer.parseInt(avence.getText());
//       trim=Integer.parseInt(trimnbr.getText());
      
//        if (LB>0 && LB<=10 ) {
//        	FR=1936.40 ;
//                fraibrachement.setText(String.valueOf(FR));
//        	
//        }
//        else if (LB>10 && LB<=20 )   {
//        	FR=2572.92 ;
//                fraibrachement.setText(String.valueOf(FR));
//        	
//        }
//        else  if (LB>20 && LB<=40 ){
//        	FR=3604.22 ;
//                fraibrachement.setText(String.valueOf(FR));
//        	
//        }
//        else {
//        	FR=(65.68*LB)+1846.35;
//                fraibrachement.setText(String.valueOf(FR));
//        	
//        }
//        fraibrachement.setText(String.valueOf(FR));
        
         if (NBR==0 || NBR==1 || NBR==2) {
        	n=0;
        	
        }
        else if (NBR==3) {
        	n=1;
        	
        }
        else {
        	n=2;
        	
        }
        TR = P0*(Math.sqrt(R+r*n)) ;
//        
//           taxeRE.setText(String.valueOf(TR));
         ///////////////////////////////////////////////////
//         if(comptant.isSelected()){
//                       
//        prix=(FR+TR+100+6.42*0.0025)+20;}
//        			total.setText(String.valueOf(prix));
//        fraibrachement.setText(String.valueOf(FR));
//        taxeRE.setText(String.valueOf(TR));
//        provision.setText(String.valueOf(PR));
//        redevancef.setText(String.valueOf(FR));
//        autresFrais.setText(String.valueOf(AF));
//        total.setText(String.valueOf(prix));
         }
         
         
         
         
//              credit = FR+TR ;
//              prix=(Cra*C+RF+PR*0.0025+20);
//        fraibrachement.setText(String.valueOf(FR));
//        taxeRE.setText(String.valueOf(TR));
//        provision.setText(String.valueOf(PR));
//        redevancef.setText(String.valueOf(FR));
//        autresFrais.setText(String.valueOf(AF));
//        total.setText(String.valueOf(prix));
//        BS.setText(String.valueOf(credit));
                }
             
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbActionPerformed

    private void provisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provisionActionPerformed

    private void comptantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comptantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comptantActionPerformed

    private void trimistrialiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trimistrialiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trimistrialiteActionPerformed

    private void redevancefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redevancefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redevancefActionPerformed

    private void autresFraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autresFraisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autresFraisActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BS;
    private javax.swing.JTextField autresFrais;
    private javax.swing.JTextField avence;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton comptant;
    private javax.swing.JTextField fraibrachement;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField lb;
    private javax.swing.JTextField nbrtt;
    private javax.swing.JTextField provision;
    private javax.swing.JTextField redevancef;
    private javax.swing.JTextField sup;
    private javax.swing.JTextField supEtage;
    private javax.swing.JTextField taxeRE;
    private javax.swing.JTextField total;
    private javax.swing.JRadioButton trimistrialite;
    private javax.swing.JTextField trimnbr;
    // End of variables declaration//GEN-END:variables
}
